### ISSUE TITLE
addon

### ISSUE THREAD

**Issue by Zoom-Adr** [graffic/plugin.video.ais_playbox_unofficial#1]
can u create addon for singtel tv go?

**Comment by graffic** [comment]
Don't think so. But I can help you to build one: not only in the Kodi part (the easy part), but learning how Singel tv go works.

**Comment by Zoom-Adr** [comment]
Can u try?


Regards,
Syafiq
________________________________

**Comment by graffic** [comment]
In the way I do it. I cannot try. I need access to the device/software while it works and usually this means also being on the network of the provider. Sorry.
