### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by dynjo** [graffic/plugin.video.ais_playbox_unofficial#2]
I suspect AIS have changed their S3 bucket somehow as this URL no longer works:

[https://sifvideostore.s3.amazonaws.com/AIS/json/Page/NewTV.json.gz](https://sifvideostore.s3.amazonaws.com/AIS/json/Page/NewTV.json.gz)

**Comment by graffic** [comment]
Ok, I guess I found the new url. Channels now appear on Kodi. Give it a try.

BTW: Thank you very much for the bug details. It helped a lot to focus the efforts searching for the new url.
