### ISSUE TITLE
Not getting any stream URLs

### ISSUE THREAD

**Issue by dynjo** [graffic/plugin.video.ais_playbox_unofficial#3]
Looks like they have changed something about the response from

`https://playbox.ais.co.th/AISWeb/ServiceCheckAssetEntitlementByUserId.aspx`

It now returns an empty response (200) on that URL.

**Comment by dynjo** [comment]
Ignore that, looks like the user id's changed, updated and working again.

**Comment by graffic** [comment]
Ouf! good to know. Thanks!

I didn't have much time to take a look at it these past days.
